### PR TITLE
Some compartibility propositions

### PR DESCRIPTION
**Pull request by makise-homura**
- Fixing issue #83 (another attempt, added specific cmake script to make parameter checks the way we really want, not the way that legacy cmake modules do)
- Reintroducing ASAN check in addition to UBSAN, as we may do it now
- Added checking for -Wpedantic and -Wnull-dereference for older compilers

### CODE REVIEW

**Comment by Akaricchi** [comment]
Actually curious, what relevant compiler doesn't support `-Wpedantic`? Some really old GCC versions? If that's a problem, we could just revert it to `-pedantic`. That's an older (now deprecated) flag that does the same thing.

I'm not sure about the `-Wnull-dereference` check either. It's not a very important warning so I'd rather just remove it. But an ideal solution would be to somehow make GCC just ignore unrecognized flags. Clang just prints a message, for example. This way we could enable some useful GCC7 and clang warnings too (switch fallthrough and local shadowing, for example).

**Comment by makise-homura** [comment]
>That's an older (now deprecated) flag that does the same thing.
Maybe use `-Wpedantic` if check succeeds, and `-pedantic` otherwise? To not broke compartibility with those compilers that do not support `-Wpedantic`, but use non-deprecated thing if compiler supports it.

>But an ideal solution would be to somehow make GCC just ignore unrecognized flags.
Well, that would be ideal, but I think that's some king of gcc philosophy like "reject everything non-understandable and forbid changing this behavior". I see a lot of places where it will be a lot easier to just do something like `CFLAGS=-fignore-unknown-params make all` instead of grepping makefiles for unknown options, but unfortunately it looks like gcc is strictly against this way...

**Comment by laochailan** [comment]
Do we need that level of compatibility for debug builds? If the release builds work on every toaster that is okay, but maybe we can expect developers to have a modern compiler (or clang). Our cmake file is already very complicated.

Alternatively create a SuperUberDebug build type and move the new stuff there.

**Comment by makise-homura** [comment]
>Our cmake file is already very complicated.

I have seen build configuration system for Intel DPDK once, so after that I don't see anything else as too complicated. :)

>Alternatively create a SuperUberDebug build type

That's another way. Because debug (when you try to figure out what's going on on your system when Taisei runs) and source checking (when you enable all warnings and stuff) are a bit different modes.

**Comment by makise-homura** [comment]
I just moved checking stuff to a separate module and made some cleaning in src/CMakeLists.txt. Now these checks looks there quite more simple than before.

If there'll be need in another compile/link-time parameter checks, this module may be used for this too, I hope.

**Comment by laochailan** [comment]
The way you did looks neat. :)

Kind of sad one has to do all this boilerplate stuff just to do something that should be somehow cmake’s job.

**Comment by makise-homura** [comment]
Thanks :) I tried to make this such a way that reusable cmake code should be not in project file, but in a separate module that may be used wherever it will be need for it - as long it is independent from the project specifics.
Also, I wonder too why did not anyone implemented this stuff before in standard cmake modules...

**Pull request merged**
